
version: '3.8'

services:
  # FastAPI Application Service
  api:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: semantic_qa_api
    env_file:
      - .env # Load environment variables from .env file
    volumes:
      - ./app:/app/app # Mount local app directory for live code reloading
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    depends_on:
      - qdrant # Ensure qdrant starts before the api service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload # Override CMD for dev

  # Qdrant Vector Database Service
  qdrant:
    image: qdrant/qdrant:latest # Use the official Qdrant image
    container_name: qdrant_db
    ports:
      - "6333:6333" # gRPC port
      - "6334:6334" # REST API port
    volumes:
      - qdrant_storage:/qdrant/storage # Persist Qdrant data using a named volume
 
volumes:
  qdrant_storage: {} # Define the named volume for Qdrant persistence